// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	v1alpha1 "github.com/estenrye/provider-netdata/apis/room/v1alpha1"
	v1alpha11 "github.com/estenrye/provider-netdata/apis/space/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this RoomMember.
func (mg *RoomMember) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.RoomID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.RoomIDRef,
		Selector:     mg.Spec.ForProvider.RoomIDSelector,
		To: reference.To{
			List:    &v1alpha1.RoomList{},
			Managed: &v1alpha1.Room{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.RoomID")
	}
	mg.Spec.ForProvider.RoomID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.RoomIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SpaceID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.SpaceIDRef,
		Selector:     mg.Spec.ForProvider.SpaceIDSelector,
		To: reference.To{
			List:    &v1alpha11.SpaceList{},
			Managed: &v1alpha11.Space{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SpaceID")
	}
	mg.Spec.ForProvider.SpaceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SpaceIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.RoomID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.RoomIDRef,
		Selector:     mg.Spec.InitProvider.RoomIDSelector,
		To: reference.To{
			List:    &v1alpha1.RoomList{},
			Managed: &v1alpha1.Room{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.RoomID")
	}
	mg.Spec.InitProvider.RoomID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.RoomIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SpaceID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.SpaceIDRef,
		Selector:     mg.Spec.InitProvider.SpaceIDSelector,
		To: reference.To{
			List:    &v1alpha11.SpaceList{},
			Managed: &v1alpha11.Space{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.SpaceID")
	}
	mg.Spec.InitProvider.SpaceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.SpaceIDRef = rsp.ResolvedReference

	return nil
}
