//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagerdutyChannel) DeepCopyInto(out *PagerdutyChannel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagerdutyChannel.
func (in *PagerdutyChannel) DeepCopy() *PagerdutyChannel {
	if in == nil {
		return nil
	}
	out := new(PagerdutyChannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PagerdutyChannel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagerdutyChannelInitParameters) DeepCopyInto(out *PagerdutyChannelInitParameters) {
	*out = *in
	if in.AlertEventsURL != nil {
		in, out := &in.AlertEventsURL, &out.AlertEventsURL
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	out.IntegrationKeySecretRef = in.IntegrationKeySecretRef
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RepeatNotificationMin != nil {
		in, out := &in.RepeatNotificationMin, &out.RepeatNotificationMin
		*out = new(float64)
		**out = **in
	}
	if in.RoomsID != nil {
		in, out := &in.RoomsID, &out.RoomsID
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagerdutyChannelInitParameters.
func (in *PagerdutyChannelInitParameters) DeepCopy() *PagerdutyChannelInitParameters {
	if in == nil {
		return nil
	}
	out := new(PagerdutyChannelInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagerdutyChannelList) DeepCopyInto(out *PagerdutyChannelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PagerdutyChannel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagerdutyChannelList.
func (in *PagerdutyChannelList) DeepCopy() *PagerdutyChannelList {
	if in == nil {
		return nil
	}
	out := new(PagerdutyChannelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PagerdutyChannelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagerdutyChannelObservation) DeepCopyInto(out *PagerdutyChannelObservation) {
	*out = *in
	if in.AlertEventsURL != nil {
		in, out := &in.AlertEventsURL, &out.AlertEventsURL
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RepeatNotificationMin != nil {
		in, out := &in.RepeatNotificationMin, &out.RepeatNotificationMin
		*out = new(float64)
		**out = **in
	}
	if in.RoomsID != nil {
		in, out := &in.RoomsID, &out.RoomsID
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SpaceID != nil {
		in, out := &in.SpaceID, &out.SpaceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagerdutyChannelObservation.
func (in *PagerdutyChannelObservation) DeepCopy() *PagerdutyChannelObservation {
	if in == nil {
		return nil
	}
	out := new(PagerdutyChannelObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagerdutyChannelParameters) DeepCopyInto(out *PagerdutyChannelParameters) {
	*out = *in
	if in.AlertEventsURL != nil {
		in, out := &in.AlertEventsURL, &out.AlertEventsURL
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	out.IntegrationKeySecretRef = in.IntegrationKeySecretRef
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RepeatNotificationMin != nil {
		in, out := &in.RepeatNotificationMin, &out.RepeatNotificationMin
		*out = new(float64)
		**out = **in
	}
	if in.RoomsID != nil {
		in, out := &in.RoomsID, &out.RoomsID
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SpaceID != nil {
		in, out := &in.SpaceID, &out.SpaceID
		*out = new(string)
		**out = **in
	}
	if in.SpaceIDRef != nil {
		in, out := &in.SpaceIDRef, &out.SpaceIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.SpaceIDSelector != nil {
		in, out := &in.SpaceIDSelector, &out.SpaceIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagerdutyChannelParameters.
func (in *PagerdutyChannelParameters) DeepCopy() *PagerdutyChannelParameters {
	if in == nil {
		return nil
	}
	out := new(PagerdutyChannelParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagerdutyChannelSpec) DeepCopyInto(out *PagerdutyChannelSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagerdutyChannelSpec.
func (in *PagerdutyChannelSpec) DeepCopy() *PagerdutyChannelSpec {
	if in == nil {
		return nil
	}
	out := new(PagerdutyChannelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagerdutyChannelStatus) DeepCopyInto(out *PagerdutyChannelStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagerdutyChannelStatus.
func (in *PagerdutyChannelStatus) DeepCopy() *PagerdutyChannelStatus {
	if in == nil {
		return nil
	}
	out := new(PagerdutyChannelStatus)
	in.DeepCopyInto(out)
	return out
}
