// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type PagerdutyChannelInitParameters struct {

	// (String) URL for alert events
	// URL for alert events
	AlertEventsURL *string `json:"alertEventsUrl,omitempty" tf:"alert_events_url,omitempty"`

	// (Boolean) The enabled status of the Pagerduty notification
	// The enabled status of the Pagerduty notification
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String, Sensitive) Integration key
	// Integration key
	IntegrationKeySecretRef v1.SecretKeySelector `json:"integrationKeySecretRef" tf:"-"`

	// (String) The name of the Pagerduty notification
	// The name of the Pagerduty notification
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (List of String) The notification options for the Pagerduty. Valid values are: CRITICAL, WARNING, CLEAR, REACHABLE, UNREACHABLE
	// The notification options for the Pagerduty. Valid values are: `CRITICAL`, `WARNING`, `CLEAR`, `REACHABLE`, `UNREACHABLE`
	Notifications []*string `json:"notifications,omitempty" tf:"notifications,omitempty"`

	// (Number) The time interval for the Pagerduty notification to be repeated. The interval is presented in minutes and should be between 30 and 1440, or 0 to avoid repetition, which is the default.
	// The time interval for the Pagerduty notification to be repeated. The interval is presented in minutes and should be between 30 and 1440, or 0 to avoid repetition, which is the default.
	RepeatNotificationMin *float64 `json:"repeatNotificationMin,omitempty" tf:"repeat_notification_min,omitempty"`

	// (List of String) The list of room IDs to set the Pagerduty notification. If the rooms list is null, the Pagerduty notification will be applied to All rooms
	// The list of room IDs to set the Pagerduty notification. If the rooms list is null, the Pagerduty notification will be applied to `All rooms`
	RoomsID []*string `json:"roomsId,omitempty" tf:"rooms_id,omitempty"`

	// (String) The ID of the space for the Pagerduty notification
	// The ID of the space for the Pagerduty notification
	// +crossplane:generate:reference:type=github.com/estenrye/provider-netdata/apis/space/v1alpha1.Space
	SpaceID *string `json:"spaceId,omitempty" tf:"space_id,omitempty"`

	// Reference to a Space in space to populate spaceId.
	// +kubebuilder:validation:Optional
	SpaceIDRef *v1.Reference `json:"spaceIdRef,omitempty" tf:"-"`

	// Selector for a Space in space to populate spaceId.
	// +kubebuilder:validation:Optional
	SpaceIDSelector *v1.Selector `json:"spaceIdSelector,omitempty" tf:"-"`
}

type PagerdutyChannelObservation struct {

	// (String) URL for alert events
	// URL for alert events
	AlertEventsURL *string `json:"alertEventsUrl,omitempty" tf:"alert_events_url,omitempty"`

	// (Boolean) The enabled status of the Pagerduty notification
	// The enabled status of the Pagerduty notification
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) The ID of the Pagerduty notification
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name of the Pagerduty notification
	// The name of the Pagerduty notification
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (List of String) The notification options for the Pagerduty. Valid values are: CRITICAL, WARNING, CLEAR, REACHABLE, UNREACHABLE
	// The notification options for the Pagerduty. Valid values are: `CRITICAL`, `WARNING`, `CLEAR`, `REACHABLE`, `UNREACHABLE`
	Notifications []*string `json:"notifications,omitempty" tf:"notifications,omitempty"`

	// (Number) The time interval for the Pagerduty notification to be repeated. The interval is presented in minutes and should be between 30 and 1440, or 0 to avoid repetition, which is the default.
	// The time interval for the Pagerduty notification to be repeated. The interval is presented in minutes and should be between 30 and 1440, or 0 to avoid repetition, which is the default.
	RepeatNotificationMin *float64 `json:"repeatNotificationMin,omitempty" tf:"repeat_notification_min,omitempty"`

	// (List of String) The list of room IDs to set the Pagerduty notification. If the rooms list is null, the Pagerduty notification will be applied to All rooms
	// The list of room IDs to set the Pagerduty notification. If the rooms list is null, the Pagerduty notification will be applied to `All rooms`
	RoomsID []*string `json:"roomsId,omitempty" tf:"rooms_id,omitempty"`

	// (String) The ID of the space for the Pagerduty notification
	// The ID of the space for the Pagerduty notification
	SpaceID *string `json:"spaceId,omitempty" tf:"space_id,omitempty"`
}

type PagerdutyChannelParameters struct {

	// (String) URL for alert events
	// URL for alert events
	// +kubebuilder:validation:Optional
	AlertEventsURL *string `json:"alertEventsUrl,omitempty" tf:"alert_events_url,omitempty"`

	// (Boolean) The enabled status of the Pagerduty notification
	// The enabled status of the Pagerduty notification
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String, Sensitive) Integration key
	// Integration key
	// +kubebuilder:validation:Optional
	IntegrationKeySecretRef v1.SecretKeySelector `json:"integrationKeySecretRef" tf:"-"`

	// (String) The name of the Pagerduty notification
	// The name of the Pagerduty notification
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (List of String) The notification options for the Pagerduty. Valid values are: CRITICAL, WARNING, CLEAR, REACHABLE, UNREACHABLE
	// The notification options for the Pagerduty. Valid values are: `CRITICAL`, `WARNING`, `CLEAR`, `REACHABLE`, `UNREACHABLE`
	// +kubebuilder:validation:Optional
	Notifications []*string `json:"notifications,omitempty" tf:"notifications,omitempty"`

	// (Number) The time interval for the Pagerduty notification to be repeated. The interval is presented in minutes and should be between 30 and 1440, or 0 to avoid repetition, which is the default.
	// The time interval for the Pagerduty notification to be repeated. The interval is presented in minutes and should be between 30 and 1440, or 0 to avoid repetition, which is the default.
	// +kubebuilder:validation:Optional
	RepeatNotificationMin *float64 `json:"repeatNotificationMin,omitempty" tf:"repeat_notification_min,omitempty"`

	// (List of String) The list of room IDs to set the Pagerduty notification. If the rooms list is null, the Pagerduty notification will be applied to All rooms
	// The list of room IDs to set the Pagerduty notification. If the rooms list is null, the Pagerduty notification will be applied to `All rooms`
	// +kubebuilder:validation:Optional
	RoomsID []*string `json:"roomsId,omitempty" tf:"rooms_id,omitempty"`

	// (String) The ID of the space for the Pagerduty notification
	// The ID of the space for the Pagerduty notification
	// +crossplane:generate:reference:type=github.com/estenrye/provider-netdata/apis/space/v1alpha1.Space
	// +kubebuilder:validation:Optional
	SpaceID *string `json:"spaceId,omitempty" tf:"space_id,omitempty"`

	// Reference to a Space in space to populate spaceId.
	// +kubebuilder:validation:Optional
	SpaceIDRef *v1.Reference `json:"spaceIdRef,omitempty" tf:"-"`

	// Selector for a Space in space to populate spaceId.
	// +kubebuilder:validation:Optional
	SpaceIDSelector *v1.Selector `json:"spaceIdSelector,omitempty" tf:"-"`
}

// PagerdutyChannelSpec defines the desired state of PagerdutyChannel
type PagerdutyChannelSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PagerdutyChannelParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PagerdutyChannelInitParameters `json:"initProvider,omitempty"`
}

// PagerdutyChannelStatus defines the observed state of PagerdutyChannel.
type PagerdutyChannelStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PagerdutyChannelObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PagerdutyChannel is the Schema for the PagerdutyChannels API. Resource for managing centralized notifications for Pagerduty. Available only in paid plans.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,netdata}
type PagerdutyChannel struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.alertEventsUrl) || (has(self.initProvider) && has(self.initProvider.alertEventsUrl))",message="spec.forProvider.alertEventsUrl is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.enabled) || (has(self.initProvider) && has(self.initProvider.enabled))",message="spec.forProvider.enabled is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.integrationKeySecretRef)",message="spec.forProvider.integrationKeySecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.notifications) || (has(self.initProvider) && has(self.initProvider.notifications))",message="spec.forProvider.notifications is a required parameter"
	Spec   PagerdutyChannelSpec   `json:"spec"`
	Status PagerdutyChannelStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PagerdutyChannelList contains a list of PagerdutyChannels
type PagerdutyChannelList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PagerdutyChannel `json:"items"`
}

// Repository type metadata.
var (
	PagerdutyChannel_Kind             = "PagerdutyChannel"
	PagerdutyChannel_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PagerdutyChannel_Kind}.String()
	PagerdutyChannel_KindAPIVersion   = PagerdutyChannel_Kind + "." + CRDGroupVersion.String()
	PagerdutyChannel_GroupVersionKind = CRDGroupVersion.WithKind(PagerdutyChannel_Kind)
)

func init() {
	SchemeBuilder.Register(&PagerdutyChannel{}, &PagerdutyChannelList{})
}
