apiVersion: discordchannel.netdata.provider.crossplane.rye.ninja/v1alpha1
kind: DiscordChannel
metadata:
  annotations:
    meta.upbound.io/example-id: discordchannel/v1alpha1/discordchannel
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    channelType: text
    enabled: true
    name: discord notifications
    notifications:
    - CRITICAL
    - WARNING
    - CLEAR
    repeatNotificationMin: 30
    roomsId:
    - <room_id>
    spaceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    webhookUrlSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
