apiVersion: pagerdutychannel.netdata.provider.crossplane.rye.ninja/v1alpha1
kind: PagerdutyChannel
metadata:
  annotations:
    meta.upbound.io/example-id: pagerdutychannel/v1alpha1/pagerdutychannel
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    alertEventsUrl: https://events.pagerduty.com/v2/enqueue
    enabled: true
    integrationKeySecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    name: pagerduty notifications
    notifications:
    - CRITICAL
    - WARNING
    - CLEAR
    repeatNotificationMin: 30
    roomsId:
    - <room_id>
    spaceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test
