// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type RoomInitParameters struct {

	// (String) The description of the room
	// The description of the room
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The name of the room
	// The name of the room
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The ID of the space
	// The ID of the space
	// +crossplane:generate:reference:type=github.com/estenrye/provider-netdata/apis/space/v1alpha1.Space
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	SpaceID *string `json:"spaceId,omitempty" tf:"space_id,omitempty"`

	// Reference to a Space in space to populate spaceId.
	// +kubebuilder:validation:Optional
	SpaceIDRef *v1.Reference `json:"spaceIdRef,omitempty" tf:"-"`

	// Selector for a Space in space to populate spaceId.
	// +kubebuilder:validation:Optional
	SpaceIDSelector *v1.Selector `json:"spaceIdSelector,omitempty" tf:"-"`
}

type RoomObservation struct {

	// (String) The description of the room
	// The description of the room
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The ID of the room
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name of the room
	// The name of the room
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The ID of the space
	// The ID of the space
	SpaceID *string `json:"spaceId,omitempty" tf:"space_id,omitempty"`
}

type RoomParameters struct {

	// (String) The description of the room
	// The description of the room
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The name of the room
	// The name of the room
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The ID of the space
	// The ID of the space
	// +crossplane:generate:reference:type=github.com/estenrye/provider-netdata/apis/space/v1alpha1.Space
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	SpaceID *string `json:"spaceId,omitempty" tf:"space_id,omitempty"`

	// Reference to a Space in space to populate spaceId.
	// +kubebuilder:validation:Optional
	SpaceIDRef *v1.Reference `json:"spaceIdRef,omitempty" tf:"-"`

	// Selector for a Space in space to populate spaceId.
	// +kubebuilder:validation:Optional
	SpaceIDSelector *v1.Selector `json:"spaceIdSelector,omitempty" tf:"-"`
}

// RoomSpec defines the desired state of Room
type RoomSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RoomParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RoomInitParameters `json:"initProvider,omitempty"`
}

// RoomStatus defines the observed state of Room.
type RoomStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RoomObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Room is the Schema for the Rooms API. Provides a Netdata Cloud Room resource. Use this resource to manage rooms in the selected space.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,netdata}
type Room struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   RoomSpec   `json:"spec"`
	Status RoomStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RoomList contains a list of Rooms
type RoomList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Room `json:"items"`
}

// Repository type metadata.
var (
	Room_Kind             = "Room"
	Room_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Room_Kind}.String()
	Room_KindAPIVersion   = Room_Kind + "." + CRDGroupVersion.String()
	Room_GroupVersionKind = CRDGroupVersion.WithKind(Room_Kind)
)

func init() {
	SchemeBuilder.Register(&Room{}, &RoomList{})
}
