// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

// Package apis contains Kubernetes API for the provider.
package apis

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/estenrye/provider-netdata/apis/discordchannel/v1alpha1"
	v1alpha1member "github.com/estenrye/provider-netdata/apis/member/v1alpha1"
	v1alpha1noderoommember "github.com/estenrye/provider-netdata/apis/noderoommember/v1alpha1"
	v1alpha1pagerdutychannel "github.com/estenrye/provider-netdata/apis/pagerdutychannel/v1alpha1"
	v1alpha1room "github.com/estenrye/provider-netdata/apis/room/v1alpha1"
	v1alpha1roommember "github.com/estenrye/provider-netdata/apis/roommember/v1alpha1"
	v1alpha1space "github.com/estenrye/provider-netdata/apis/space/v1alpha1"
	v1alpha1apis "github.com/estenrye/provider-netdata/apis/v1alpha1"
	v1beta1 "github.com/estenrye/provider-netdata/apis/v1beta1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1member.SchemeBuilder.AddToScheme,
		v1alpha1noderoommember.SchemeBuilder.AddToScheme,
		v1alpha1pagerdutychannel.SchemeBuilder.AddToScheme,
		v1alpha1room.SchemeBuilder.AddToScheme,
		v1alpha1roommember.SchemeBuilder.AddToScheme,
		v1alpha1space.SchemeBuilder.AddToScheme,
		v1alpha1apis.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
