apiVersion: noderoommember.netdata.provider.crossplane.rye.ninja/v1alpha1
kind: RoomMember
metadata:
  annotations:
    meta.upbound.io/example-id: noderoommember/v1alpha1/roommember
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    nodeNames:
    - node1
    - node2
    roomIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    rule:
    - action: INCLUDE
      clause:
      - label: role
        negate: false
        operator: equals
        value: parent
      - label: environment
        negate: false
        operator: equals
        value: production
      description: Description of the rule
    spaceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
