apiVersion: space.netdata.provider.crossplane.rye.ninja/v1alpha1
kind: Space
metadata:
  annotations:
    meta.upbound.io/example-id: space/v1alpha1/space
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    description: Created by Terraform
    name: MyTestingSpace
