//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackChannel) DeepCopyInto(out *SlackChannel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackChannel.
func (in *SlackChannel) DeepCopy() *SlackChannel {
	if in == nil {
		return nil
	}
	out := new(SlackChannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlackChannel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackChannelInitParameters) DeepCopyInto(out *SlackChannelInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RepeatNotificationMin != nil {
		in, out := &in.RepeatNotificationMin, &out.RepeatNotificationMin
		*out = new(float64)
		**out = **in
	}
	if in.RoomsID != nil {
		in, out := &in.RoomsID, &out.RoomsID
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RoomsIDRefs != nil {
		in, out := &in.RoomsIDRefs, &out.RoomsIDRefs
		*out = make([]v1.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RoomsIDSelector != nil {
		in, out := &in.RoomsIDSelector, &out.RoomsIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.SpaceID != nil {
		in, out := &in.SpaceID, &out.SpaceID
		*out = new(string)
		**out = **in
	}
	if in.SpaceIDRef != nil {
		in, out := &in.SpaceIDRef, &out.SpaceIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.SpaceIDSelector != nil {
		in, out := &in.SpaceIDSelector, &out.SpaceIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	out.WebhookURLSecretRef = in.WebhookURLSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackChannelInitParameters.
func (in *SlackChannelInitParameters) DeepCopy() *SlackChannelInitParameters {
	if in == nil {
		return nil
	}
	out := new(SlackChannelInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackChannelList) DeepCopyInto(out *SlackChannelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SlackChannel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackChannelList.
func (in *SlackChannelList) DeepCopy() *SlackChannelList {
	if in == nil {
		return nil
	}
	out := new(SlackChannelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlackChannelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackChannelObservation) DeepCopyInto(out *SlackChannelObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RepeatNotificationMin != nil {
		in, out := &in.RepeatNotificationMin, &out.RepeatNotificationMin
		*out = new(float64)
		**out = **in
	}
	if in.RoomsID != nil {
		in, out := &in.RoomsID, &out.RoomsID
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SpaceID != nil {
		in, out := &in.SpaceID, &out.SpaceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackChannelObservation.
func (in *SlackChannelObservation) DeepCopy() *SlackChannelObservation {
	if in == nil {
		return nil
	}
	out := new(SlackChannelObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackChannelParameters) DeepCopyInto(out *SlackChannelParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RepeatNotificationMin != nil {
		in, out := &in.RepeatNotificationMin, &out.RepeatNotificationMin
		*out = new(float64)
		**out = **in
	}
	if in.RoomsID != nil {
		in, out := &in.RoomsID, &out.RoomsID
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RoomsIDRefs != nil {
		in, out := &in.RoomsIDRefs, &out.RoomsIDRefs
		*out = make([]v1.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RoomsIDSelector != nil {
		in, out := &in.RoomsIDSelector, &out.RoomsIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.SpaceID != nil {
		in, out := &in.SpaceID, &out.SpaceID
		*out = new(string)
		**out = **in
	}
	if in.SpaceIDRef != nil {
		in, out := &in.SpaceIDRef, &out.SpaceIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.SpaceIDSelector != nil {
		in, out := &in.SpaceIDSelector, &out.SpaceIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	out.WebhookURLSecretRef = in.WebhookURLSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackChannelParameters.
func (in *SlackChannelParameters) DeepCopy() *SlackChannelParameters {
	if in == nil {
		return nil
	}
	out := new(SlackChannelParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackChannelSpec) DeepCopyInto(out *SlackChannelSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackChannelSpec.
func (in *SlackChannelSpec) DeepCopy() *SlackChannelSpec {
	if in == nil {
		return nil
	}
	out := new(SlackChannelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackChannelStatus) DeepCopyInto(out *SlackChannelStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackChannelStatus.
func (in *SlackChannelStatus) DeepCopy() *SlackChannelStatus {
	if in == nil {
		return nil
	}
	out := new(SlackChannelStatus)
	in.DeepCopyInto(out)
	return out
}
