apiVersion: noderoommember.netdata.provider.crossplane.rye.ninja/v1alpha1
kind: RoomMember
metadata:
  annotations:
    meta.upbound.io/example-id: noderoommember/v1alpha1/roommember
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    nodeNames:
    - test-cluster
    - test-cluster-k8s-state
    roomIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test
    rule:
    - action: INCLUDE
      clause:
      - label: role
        negate: false
        operator: equals
        value: parent
      - label: release
        negate: false
        operator: equals
        value: netdata
    - action: INCLUDE
      clause:
      - label: role
        negate: false
        operator: equals
        value: child
      - label: release
        negate: false
        operator: equals
        value: netdata
      description: Description of the rule
    spaceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test
