apiVersion: slackchannel.netdata.provider.crossplane.rye.ninja/v1alpha1
kind: SlackChannel
metadata:
  annotations:
    meta.upbound.io/example-id: slackchannel/v1alpha1/slackchannel
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    enabled: true
    name: slack notifications
    notifications:
    - CRITICAL
    - WARNING
    - CLEAR
    repeatNotificationMin: 30
    roomsIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test
    spaceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test
    webhookUrlSecretRef:
      key: webhook-url
      name: slack-webhook-secret
      namespace: upbound-system
